Master-to-gateway migration conversion
openmotics/gateway pull request #1072
Opened 2022-03-18 13:51 UTC by khenderick

2022-03-22 08:10 UTC, svanscho requested changes

2022-03-22 08:10 UTC, svanscho commented on src/gateway/migrations/thermostats.py
> +                valve_to_thermostat.priority = valve_priority
probably a commit is down the stack, but perhaps it would be good to add one here too in order to not forget?

2022-03-22 08:10 UTC, svanscho commented on src/gateway/migrations/thermostats.py
> -                preset.save()
same comment as above

2022-03-22 08:10 UTC, svanscho commented on src/gateway/migrations/thermostats.py
> +            db.add(schedule)
and here again

2022-03-22 10:51 UTC, svanscho approved these changes

2022-03-22 10:51 UTC, svanscho commented
approved, pending real validation on a gateway

2022-03-23 09:22 UTC, LnL7 approved these changes

2022-03-23 09:23 UTC, khenderick commented
Intermediate merge in, since now everything is included to run on a physical gateway. Will continue testing and open another PR if fixes are still needed.

2022-03-23 09:23 UTC, merged