Add support for HVAC setpoint API
openmotics/gateway pull request #1152
Opened 2022-05-12 14:25 UTC by pstragier

Add HVAC APIs (get & set) for communicating setpoint & mode to HVAC module

2022-05-19 04:09 UTC, khenderick approved these changes

2022-05-19 07:58 UTC, svanscho commented on src/gateway/hvac_controller.py
> +class HvacController(BaseController):
@pstragier

2022-05-19 07:58 UTC, svanscho requested changes
WDYT?

2022-05-19 08:54 UTC, bneyr commented on src/gateway/hvac_controller.py
> +class HvacController(BaseController):
@svanscho wat heeft de HVAC functionaliteit te maken met de de ModuleController?
Lijkt me vreemd om dit samen te steken met module discovery

2022-05-19 09:26 UTC, svanscho commented on src/gateway/hvac_controller.py
> +class HvacController(BaseController):
HVAC is een module afaik. Waar je 'settings' naar kan wegschrijven.

2022-05-19 09:48 UTC, bneyr commented on src/gateway/hvac_controller.py
> +class HvacController(BaseController):
Module abstraction for HVAC is not MVP.

Hoe we dat gaan doen zou ik eens samen deftig bekijken, maar is voor ons niet prio.

Ik dacht dat je bedoelde om the setpoint write functies in de modulecontroller te steken, wat ik raar zou vinden.

2022-05-19 10:11 UTC, svanscho commented on src/gateway/hvac_controller.py
> +class HvacController(BaseController):
If I'm not mistaken, one can now send setpoints to any random sensor on the master. What happens if you set a setpoint on a sensor that is not a mixer tap? 

At least some form of very basic validation can be done on the API level. If it is too much work/hassle for MVP to model/sync the mixer taps, can we then at least block sending setpoints to sensors which are not mixer taps?

2022-05-23 08:58 UTC, svanscho approved these changes

2022-05-24 08:20 UTC, merged