api call fix
openmotics/gateway pull request #1271
Opened 2022-10-21 11:56 UTC by hendrikVandeput

2022-10-21 12:15 UTC, fcaponOM approved these changes

2022-10-21 12:31 UTC, svanscho requested changes

2022-10-21 12:31 UTC, svanscho commented on src/gateway/thermostat/gateway/thermostat_controller_gateway.py
> +                    index = 0  # temporary fix to keep front-end happy while outfasing thermostat groups
I don't think this shortcut is acceptable

2022-10-21 13:14 UTC, LnL7 approved these changes

2022-10-28 13:32 UTC, svanscho approved these changes

2022-10-28 13:40 UTC, merged