id and numbers seperated
openmotics/gateway pull request #1275
Opened 2022-10-28 12:10 UTC by felix-capon

id and numbers seperated

2022-10-28 15:17 UTC, LnL7 requested changes
Both serialisation return values and deserialisation inputs determine the format of the v0 API and as a result can't just be changed. Only once functions interact with DTO objects are the contracts in internal.
Same goes for the metrics generated data.

2022-10-28 15:17 UTC, LnL7 commented on src/gateway/api/serializers/thermostat.py
> +        data = {'number': thermostat_dto.number,
```suggestion
        data = {'id': thermostat_dto.number,
```

2022-10-28 15:17 UTC, LnL7 commented on src/gateway/api/serializers/thermostat.py
> +        data = {'number': thermostat_group_status_dto.number,
```suggestion
        data = {'id': thermostat_group_status_dto.number,
```

2022-10-28 15:17 UTC, LnL7 commented on src/gateway/metrics_collector.py
> +                                          tags={'number': 'G.{0}'.format(status.number)},
```suggestion
                                          tags={'id': 'G.{0}'.format(status.number)},
```

2022-11-02 10:09 UTC, felix-capon commented
Nomenclature of id's and numbers of thermostats cleaned. Changes should not have any functional impact.

2022-11-02 10:26 UTC, LnL7 requested changes

2022-11-02 10:26 UTC, LnL7 commented on src/gateway/api/serializers/thermostat.py
> +            data['id'].append({'number': status.number,
```suggestion
            data['id'].append({'id': status.number,
```

2022-11-02 10:26 UTC, LnL7 commented on testing/unittests/gateway_tests/webservice_test.py
> +                'number': 0,
This is api data so implies there's a breaking change somewhere.

2022-11-02 13:49 UTC, LnL7 requested changes

2022-11-02 13:49 UTC, LnL7 commented on src/gateway/hal/mappers_classic/thermostat.py
> +        return ThermostatDTO(number=data['number'],
The data here comes from the gen2 eeprom configuration, etc. ThermostatConfiguration which still uses an `id` field to represent the number slots used by the firmware.

```suggestion
        return ThermostatDTO(number=data['id'],
```

2022-11-02 13:49 UTC, LnL7 commented on src/gateway/hal/mappers_classic/thermostat.py
> +        data = {'number': thermostat_dto.number}  # type: Dict[str, Any]
Same as above

2022-11-02 13:49 UTC, LnL7 commented on src/gateway/thermostat/master/thermostat_controller_master.py
> +            statusses.append(ThermostatStatusDTO(number=thermostat['number'],
The data tracked by the status cache wasn't converted so will still use `id` fields, ideally this code would be converted to use the DTO objects instead of dicts.

2022-11-02 13:49 UTC, LnL7 commented on src/gateway/api/serializers/thermostat.py
> +        thermostat_group_dto = ThermostatGroupDTO(number=api_data.get('number', 0))
```suggestion
        thermostat_group_dto = ThermostatGroupDTO(number=api_data.get('id', 0))
```

2022-11-02 16:55 UTC, felix-capon commented
All ID/Number discrepancies should be resolved.

2022-11-03 09:39 UTC, LnL7 approved these changes

2022-11-03 09:40 UTC, merged