Bugfix/ventilation level
openmotics/gateway pull request #1331
Opened 2023-01-18 10:05 UTC by felix-capon

2023-01-21 22:30 UTC, hendrikVandeput approved these changes

2023-01-24 08:28 UTC, svanscho requested changes

2023-01-24 08:28 UTC, svanscho commented on src/gateway/api/serializers/ventilation.py
> +                'amount_of_levels': amount_of_levels,
is this a deliberate change?

2023-01-24 08:28 UTC, svanscho commented on src/plugin_runtime/connectors/ventilation.py
> +    def register(self, external_id, name, amount_of_levels, min_level, max_level, device_type, device_vendor, device_serial):
I'd expect the min_level and max_level as optional kwargs at the end of the signature for backwards compatibility.
Right now, older plugins will not be able to register ventilation units any longer. I thought the whole purposes was to extend with backwards compatibility.

```def register(self, external_id, name, amount_of_levels, device_type, device_vendor, device_serial, min_level=None, max_level=None ):```

2023-01-24 08:28 UTC, svanscho commented on src/gateway/models.py
> +    min_level = Column(Integer, nullable=False, default=0)
why default 0 and with nullable False? I'd expect these values can be None, meaning they are not defined and only the amount_of_levels will be taken into account.

2023-01-24 08:28 UTC, svanscho commented on src/gateway/dto/ventilation.py
> +            if max_level == 0:
would expect if max_level is None here

2023-01-24 08:28 UTC, svanscho commented on src/gateway/dto/ventilation.py
> +            min_level = 0
and both None here too

2023-01-24 08:28 UTC, svanscho commented on src/gateway/api/serializers/ventilation.py
> +                'min_level': Toolbox.denonify(ventilation_dto.min_level, 0),
Not sure why None(s) are not allowed (see below).

2023-01-24 08:30 UTC, svanscho commented
@felix-capon few comments, but I'll let @LnL7 have a look too. He is more into the JSON schema things.

Regardless of my comments, can you squash the commits for a more cleaner merge?

2023-01-24 09:09 UTC, LnL7 commented on src/gateway/api/serializers/ventilation.py
> +            ventilation_dto.min_level = Toolbox.nonify(api_data['min_level'], '')
The second argument of notify/denonify is used for conversion of None values in dto fields used throughout the code internally. This is because historically many of the configuration apis on the gateway used 255 instead of the json `null`. So `""` should definitely not be used for fields that are expected to container integers.

```
Toolbox.deserializer({"name": ""}) => VentilationDTO(name=None)
Toolbox.serialize(VentilationDTO(name=None)) => {"name":""}
```

The exact values used in this serializer are only used by cloud syncing IIRC, everything in the frontend uses the new `/api/ventilation/units` endpoint with a schema which has a more flexible approach for changes.

2023-01-25 10:03 UTC, felix-capon commented on src/gateway/api/serializers/ventilation.py
> +                'amount_of_levels': amount_of_levels,
The denonification is done a few lines above. This is because the max amount needs this value for denonification.

2023-01-25 10:03 UTC, felix-capon commented on src/plugin_runtime/connectors/ventilation.py
> +    def register(self, external_id, name, amount_of_levels, min_level, max_level, device_type, device_vendor, device_serial):
Applied

2023-01-25 10:03 UTC, felix-capon commented on src/gateway/dto/ventilation.py
> +            if max_level == 0:
Applied

2023-01-25 10:03 UTC, felix-capon commented on src/gateway/api/serializers/ventilation.py
> +                'min_level': Toolbox.denonify(ventilation_dto.min_level, 0),
Applied

2023-01-25 10:04 UTC, felix-capon commented on src/gateway/dto/ventilation.py
> +    def __init__(self, name, device_type, device_vendor, device_serial, amount_of_levels, min_level=0, max_level=0, id=None, external_id=None):
Min and max are now optional.

2023-01-25 10:06 UTC, felix-capon commented on src/gateway/api/serializers/ventilation.py
> +            ventilation_dto.min_level = Toolbox.nonify(api_data['min_level'], '')
Min and max can now be left None (Validation happens later). Amount of levels is denonified to integer.

2023-01-26 15:08 UTC, svanscho requested changes

2023-01-26 15:08 UTC, svanscho commented on src/gateway/dto/ventilation.py
> +    def validate_levels(min_level, max_level, amount_of_levels):
perhaps we should declare this outside of the dtos as a helper function?

2023-01-26 15:08 UTC, svanscho commented on src/gateway/models.py
> +    max_level = Column(Integer, nullable=False, default=0)
remove the defaults

2023-01-26 15:08 UTC, svanscho commented on src/gateway/dto/ventilation.py
> +    def validate_levels(min_level, max_level, amount_of_levels):
we should raise invalid combinations e.g. max_level < min_level

2023-01-26 15:08 UTC, svanscho commented on testing/unittests/gateway_tests/webservice_test.py
> +                'min_level': 0,
shouldn't this raise an error?

Would also add a test with amount_of_levels > 1

2023-01-26 15:08 UTC, svanscho commented on testing/unittests/plugins_tests/connector_test.py
> +    def register(self, external_id, name, amount_of_levels, min_level, max_level, device_type, device_vendor, device_serial):
add None kwargs

2023-01-26 15:49 UTC, svanscho requested changes

2023-01-26 15:49 UTC, svanscho commented on src/gateway/dto/ventilation.py
> +    def validate_levels(min_level, max_level, amount_of_levels):
```
if min is None or max is None:
    if amount_of_levels == 1:
         min, max = 1, 1
    if amount_of_levels >= 2:
          min, max = 1, amount_of_levels 
 if max < min or amount_of_levels < 1:
     raise ValueError
  ```

2023-02-02 08:11 UTC, LnL7 submitted a review, later dismissed

2023-02-02 08:11 UTC, LnL7 commented on src/gateway/api/serializers/ventilation.py
>              ventilation_dto.amount_of_levels = Toolbox.nonify(api_data['amount_of_levels'], '')
```suggestion
            ventilation_dto.amount_of_levels = api_data['amount_of_levels']
```

2023-02-02 08:11 UTC, LnL7 commented on src/gateway/api/serializers/ventilation.py
> +            ventilation_dto.min_level = Toolbox.nonify(api_data['min_level'], '')
```suggestion
            ventilation_dto.min_level = api_data['min_level']
```

2023-02-02 08:11 UTC, LnL7 commented on src/gateway/api/serializers/ventilation.py
> +            ventilation_dto.max_level = Toolbox.nonify(api_data['max_level'], '')
```suggestion
            ventilation_dto.max_level = api_data['max_level']
```

2023-02-03 11:17 UTC, LnL7 approved these changes

2023-02-03 14:19 UTC, merged