master communication heartbeat
openmotics/gateway pull request #484
Opened 2020-10-15 10:33 UTC by LnL7

2020-10-16 04:12 UTC, khenderick requested changes
Few remarks. Also implement the functionality in the core communicator.

2020-10-16 04:12 UTC, khenderick commented on src/gateway/hal/master_controller_classic.py
>          time.sleep(5)
Maybe it's better to move this sleep into the if-statement. Similar for the Core implementation.

2020-10-16 04:12 UTC, khenderick commented on src/gateway/watchdog.py
> +        calls_timedout = [call for call in stats['calls_timedout']]
You're not using the `start_time` variable anymore. This was to that if the watchdog is started it doesn't take previous statistics into account. If a test for example turns of the watchdog to e.g. validate certain behavior and tons of timeouts will be generated, and then the watchdog is restarted, it might immediately trigger on those previous timed out calls.

2020-10-16 04:12 UTC, khenderick commented on src/master/classic/master_communicator.py
> +        # self.__communication_stats = {'calls_succeeded': [],
If not needed anymore, let's remove these comments.. On the other hand, does it make sense to reset the stats when the communicator restarts?

2020-10-16 04:12 UTC, khenderick commented on src/power/power_communicator.py
> +            logger.warning('Observed master communication failures, but not enough calls')
`energy` instead of `master`

2020-10-16 04:12 UTC, khenderick commented on testing/cicd/tests/master_test.py
> +    toolbox.dut.get('/reset_master', {'power_on': False})
What's the impact of this test to other tests if it leaves the master powered off?

2020-10-19 08:26 UTC, LnL7 commented on src/master/classic/master_communicator.py
> +        # self.__communication_stats = {'calls_succeeded': [],
I did this initially to handle the condition from the comment above, but doing so significantly delays any action taken by the watchdog (with the current settings).

2020-10-19 08:29 UTC, LnL7 commented on testing/cicd/tests/master_test.py
> +    toolbox.dut.get('/reset_master', {'power_on': False})
The watchdog is expected to power on the master again.

2020-10-21 04:05 UTC, khenderick requested changes

2020-10-21 04:05 UTC, khenderick commented on src/master/core/core_communicator.py
> +    def reset_communication_statistics(self):
This seems the get, and above the reset.

2020-10-22 04:01 UTC, khenderick approved these changes

2020-10-22 08:24 UTC, khenderick approved these changes

2020-10-22 08:52 UTC, merged