Skip update for energy modules when the bus isn't configured
openmotics/gateway pull request #517
Opened 2020-12-02 13:16 UTC by khenderick

2020-12-03 14:18 UTC, svanscho requested changes

2020-12-03 14:18 UTC, svanscho commented on src/power_bootloader.py
> +
perhaps split this over multiple lines with detailed log line? saves another round trip of checking

if store is None:
    logger.info('Energy store not found')
if communicator is None:
    logger.info('Energy bus is disabled')
   ....

2020-12-04 05:11 UTC, khenderick commented on src/power_bootloader.py
> +
As you can see here (https://github.com/openmotics/gateway/pull/517/files#diff-8a1a4eabd8ce905fc8d6a051b33944b4eba0b36fcd7d9732cdbb0185393cf77fR348) both will only be `None` when the bus is disabled.

2020-12-04 07:42 UTC, svanscho commented on src/power_bootloader.py
> +
I can't clearly see the path, but I would assume there is a possibility the db is corrupt/missing while the serial is configured. I am not saying it's likely, but possible.
Sidenote: is it planned somewhere to also migrate this energy power store to the general gateway.db?

2020-12-04 09:08 UTC, khenderick commented on src/power_bootloader.py
> +
There's a ticket for that

2020-12-04 09:11 UTC, khenderick commented on src/power_bootloader.py
> +
Updated

2020-12-04 10:07 UTC, svanscho approved these changes

2020-12-04 10:12 UTC, merged