Adding PluginWeb(Request/Response) objects to send between gateway an…
openmotics/gateway pull request #559
Opened 2021-01-28 08:35 UTC by ptuytsch

…d plugin

2021-01-29 06:16 UTC, khenderick requested changes
A few more general remarks:
* Make sure to validate dependencies (e.g. base64) on older devices (use for example our Angstrom DUT) whether they are installed or not. If not, we'll have to provide a wheel.
* In the plugin tests, there's apart where "real" plugins are created, make sure to validate a few posibilities/versions there as well. Not only a static (de)serialization test, but also a full runner/runtime test.

2021-01-29 06:16 UTC, khenderick commented on src/plugin_runtime/runtime.py
> +            if 'plugin_web_request' in kwargs:
It's the best idea to check the decorated version here. If it's not version 2, the request object should never be given, as this might be some parameter currently used for something else. It's only when version 2 is explicitly used that we can be sure that this would behave as expected.

2021-01-29 06:16 UTC, khenderick commented on src/plugin_runtime/runtime.py
> +
Extra whitespace not needed.

2021-01-29 06:16 UTC, khenderick commented on src/plugins/runner.py
> +        while len(vpath) > 0:
Why is that needed? You can just let it be, right?

2021-01-29 06:16 UTC, khenderick commented on src/plugins/runner.py
> +            if PluginWebResponse.is_valid_serial_representation(contents):
The if-else would not be needed if the runtime would always return a `PluginWebResponse`

2021-01-29 06:16 UTC, khenderick commented on src/plugins/runner.py
> +                kwargs = {'plugin_web_request': plugin_web_request.serialize()}
This implies that a version 2 implementation on the plugin would only receive a single keyword argument `plugin_web_request`. Wouldn't it be more elegant if the get-parameters (if any) would still be passed as kwargs (if specified)? For a lot of the cases this works very easy and straightforward.

```
@om_expose(version=2)
def one(self, param_one, param_two):
   # .../one?param_one=1&param_two=2 still works

@om_expose
def two(self, param_one, param_two):
     # .../two?param_one=1&param_two=2 still works

@om_expose(version=2)
def three(self, param_one, param_two, plugin_web_request):
   # .../three?param_one=1&param_two=2 still works, but I can also access plugin_web_request['path'] or ...['body']

@om_expose(version=2)
def four(self, plugin_web_request):
   # .../four?param_one=1&param_two=2 still works, as is plugin_web_request['path'] or ...['body'], but I'll have to load e.g. plugin_web_request['params']['param_one'] myself
```

Not sure on the last one, I might be missing something, but it looks like GET params are not possible anymore when using the request body? Should still be possible right?

2021-02-02 12:07 UTC, khenderick requested changes

2021-02-02 12:35 UTC, ptuytsch commented on src/plugin_runtime/base.py
> +            if getattr(self, var) != getattr(other, var):
The pluginWebBody is never used as a variable in the PluginWeb(Response/Request) objects. Only in the serialization and de-serialization process. But I've added it into the PluginWebBody. Better safe than sorry!

2021-02-03 12:39 UTC, khenderick approved these changes

2021-02-03 13:36 UTC, merged