Add support for indicate
openmotics/gateway pull request #598
Opened 2021-03-08 12:26 UTC by khenderick

2021-03-08 14:55 UTC, svanscho requested changes

2021-03-08 14:55 UTC, svanscho commented on src/gateway/hal/master_controller_core.py
> +        :param led_type: The module type: output/dimmer (0), input (1), sensor/temperatur (2).
typo

2021-03-08 14:55 UTC, svanscho commented on src/gateway/hal/master_controller_core.py
> +        if led_type not in [0, 1, 2]:
move to constants

2021-03-08 14:55 UTC, svanscho commented on src/gateway/hal/master_controller_core.py
> +            self._master_communicator.do_basic_action(BasicAction(action_type=8, action=200, device_nr=led_id))
can't we use the core responses as we do for the classic master?

2021-03-09 05:07 UTC, khenderick commented on src/gateway/hal/master_controller_core.py
> +            self._master_communicator.do_basic_action(BasicAction(action_type=8, action=200, device_nr=led_id))
No, the Core returns other data (basically an echo of what was requested).

2021-03-09 05:14 UTC, khenderick commented on src/gateway/hal/master_controller_core.py
> +            self._master_communicator.do_basic_action(BasicAction(action_type=8, action=200, device_nr=led_id))
No, the Core returns other data (basically an echo of what was requested).

2021-03-09 08:36 UTC, svanscho approved these changes

2021-03-09 08:40 UTC, merged