Add online flag to ventilation status
openmotics/gateway pull request #603
Opened 2021-03-11 16:44 UTC by ptuytsch

2021-03-16 14:42 UTC, svanscho requested changes

2021-03-16 14:42 UTC, svanscho commented on src/gateway/dto/ventilation.py
> +        self.timestamp = timestamp
nice shortcut can also be:
self.timestamp = timestamp or time.time()

2021-03-16 14:42 UTC, svanscho commented on src/gateway/dto/ventilation.py
> +        self.timestamp = timestamp
can we use something less generic than timestamp? e.g. last_seen or last_update?

2021-03-16 14:42 UTC, svanscho commented on src/gateway/ventilation_controller.py
> +            delta = time.time() - ventilation_status_dto.timestamp
this looks a bit duplicate with the is_connected in the DTO? It's a bit confusing to have a hardcoded value of 300 on one hand and a STATUS_TIMEOUT constant on the other side. Would either check the is_connected property here or remove the is_connected from the dto?

2021-03-16 14:42 UTC, svanscho commented on src/gateway/ventilation_controller.py
> +                del self.last_ventilation_status[ventilation_id]
I would not expect a full delete of the status, but rather make it None for all relevant fields and keep the timestamp (or the connected flag, cfr comment above)

2021-03-16 15:50 UTC, svanscho commented on src/gateway/ventilation_controller.py
> +        for ventilation_id, ventilation_status_dto in ventilation_items:
is there a reason not to use for k,v in data.iteritems()?

2021-03-16 15:52 UTC, svanscho submitted a review, later dismissed

2021-03-16 16:07 UTC, ptuytsch commented on src/gateway/ventilation_controller.py
> +        for ventilation_id, ventilation_status_dto in ventilation_items:
There was one, but now there is none indeed. The list variable has been removed.

2021-03-17 07:57 UTC, svanscho approved these changes

2021-03-17 09:07 UTC, merged