[WIP] Can FX call - see comment for logs
openmotics/gateway pull request #665
Opened 2021-04-27 15:41 UTC by Shinigami-shinto

```
Apr 27 13:24:32 OpenMotics openmotics-api[20352]: 2021-04-27 13:24:32,447 - root - INFO - Resetting CAN EEPROM, adress: 067.165.162.156

Apr 27 13:24:32 OpenMotics openmotics-api[20352]: 2021-04-27 13:24:32,456 - gateway.master.classic - DEBUG - Writing to Master serial:    83  84  82  70  88  29  67 165 162 156   0   0  67   2 196   0   0   0   0   0  13  10    STRFX.C.....C.........
Apr 27 13:24:32 OpenMotics openmotics-api[20352]: 2021-04-27 13:24:32,469 - gateway.master.classic - DEBUG - Reading from Master serial:  70  88  29  67 165    FX.C.
Apr 27 13:24:32 OpenMotics openmotics-api[20352]: 2021-04-27 13:24:32,477 - gateway.master.classic - DEBUG - Reading from Master serial: 162 156   4  67   2 200  13  10  13  10   7  13  10    ...C.........
```
Lijkt niet effectief te resetten

2021-04-28 04:04 UTC, khenderick requested changes

2021-04-28 04:04 UTC, khenderick commented on src/gateway/hal/master_controller_classic.py
> +    def can_reset(self):
Maybe call this `can_control_factory_reset` to make sure a customer doesn't think it just reboots the CAN bus or similar`

2021-04-28 04:04 UTC, khenderick commented on src/gateway/hal/master_controller_classic.py
> +        # https://wiki.openmotics.com/index.php/API_Reference_Guide#FX_-.3E_Erase_external_Eeprom_slave_modules_and_perform_factory_reset
Call the below function instead of duplicating the code.

2021-04-28 04:04 UTC, khenderick commented on src/gateway/webservice.py
> +    def can_reset(self):
Use similar naming as suggested above + Provide same "safety" checks as in the normal factory reset (e.g. credentials, extra flag, ...)

2021-05-04 10:19 UTC, Shinigami-shinto commented
It has been verified on the test system that the FX call works. Additional "full" factory_reset tests will reveal if wiping the CC EEPROM can be done by default or not.

2021-05-05 07:13 UTC, LnL7 commented on src/gateway/initialize.py
> +    # type: (MasterController, int) -> None
```suggestion
    # type: (MasterController, bool) -> None
```

2021-05-05 07:13 UTC, LnL7 commented on src/gateway/hal/master_controller_classic.py
> +    def factory_reset(self, Can=False):
Capitalized variables are not really idiomatic in python.

```suggestion
    def factory_reset(self, can=False):
```

2021-05-05 07:13 UTC, LnL7 commented on src/gateway/gateway_api.py
> +        # type: (int) -> Dict[str,Any]
```suggestion
        # type: (bool) -> Dict[str,Any]
```

2021-05-05 07:13 UTC, LnL7 commented on src/gateway/gateway_api.py
>              subprocess.check_output(['python2', 'openmotics_cli.py', 'operator', 'factory-reset'])
This command also needs to support the can flag otherwise the lockfile will never contain `factory_reset_full` to trigger the new case.

2021-05-05 07:13 UTC, LnL7 commented on src/gateway/webservice.py
> +    def factory_reset(self, username, password, confirm=False, can=False):
I think we want to wipe everything by default.

2021-05-06 08:34 UTC, LnL7 approved these changes

2021-05-06 08:46 UTC, khenderick approved these changes

2021-05-06 08:47 UTC, merged