Use named logger everywhere
openmotics/gateway pull request #700
Opened 2021-05-21 14:03 UTC by svanscho

2021-05-28 04:25 UTC, khenderick requested changes

2021-05-28 04:25 UTC, khenderick commented on src/cloud/events.py
> +            logger.exception('Error sending events to the cloud')
I would leave this to `logger.error`, as I've seen this exception often in the past, just whining about the cloud not beging available for a moment. Changing to `logger.exception` will just litter the logs and not learn new stuff about where the error comes from.

2021-05-28 04:25 UTC, khenderick commented on src/core_updater.py
> +logger = logging.getLogger('openmotics')
Use `__name__` here?

2021-05-28 04:25 UTC, khenderick commented on src/gateway/initialize.py
> +                    logging.getLogger(logger_namespace).setLevel(logging.DEBUG)
Maybe move this part to the Logger helper module we have?

2021-05-28 04:25 UTC, khenderick commented on src/vpn_service.py
> +                logger.debug('Uploading {} bytes of extra data from {}'.format(len(json.dumps(data).encode('utf-8')), collector_key))
Would there be a way to calculate this without having to `json.dump` the data twice (here and below for the complete dict)? Is this per-key statistics useful enough to add the overhead?

2021-05-28 04:29 UTC, khenderick commented
As a more general remark, since we are again tweaking the loggers, it might be a good idea to have just a new section in `openmotics.conf` like `[logging]` where we can just sepecify and override multiple loggers. Especially for more complex scenarios like "I want to have debug logging for the core communicator and slave communicator, but not for the ucan communicator.".

E.g.

```
root@OpenMotics:/opt/openmotics/etc# cat openmotics.conf
[OpenMotics]
uuid = xxx
vpn_check_url = https://staging.openmotics.com/portal/check_vpn/?uuid=%s
version = 1.18.0
controller_serial = /dev/ttyO5
passthrough_serial = /dev/ttyO1
power_serial = /dev/ttyO4
leds_i2c_address = 0x20
cloud_user = xxx
cloud_pass = xxx
platform = CLASSIC

[logging]
default_log_level = INFO
master.core.core_communicator = DEBUG
master.core.slave_communicator = DEBUG
```

2021-05-28 04:29 UTC, khenderick commented
As a more general remark, since we are again tweaking the loggers, it might be a good idea to have just a new section in `openmotics.conf` like `[logging]` where we can just sepecify and override multiple loggers. Especially for more complex scenarios like "I want to have debug logging for the core communicator and slave communicator, but not for the ucan communicator.".

E.g.

```
root@OpenMotics:/opt/openmotics/etc# cat openmotics.conf
[OpenMotics]
uuid = xxx
vpn_check_url = https://staging.openmotics.com/portal/check_vpn/?uuid=%s
version = 1.18.0
controller_serial = /dev/ttyO5
passthrough_serial = /dev/ttyO1
power_serial = /dev/ttyO4
leds_i2c_address = 0x20
cloud_user = xxx
cloud_pass = xxx
platform = CLASSIC

[logging]
default_log_level = INFO
master.core.core_communicator = DEBUG
master.core.slave_communicator = DEBUG
```

2021-05-28 06:32 UTC, svanscho commented on src/core_updater.py
> +logger = logging.getLogger('openmotics')
in the root folder everything would get logged as __main__, I discussed this with @LnL7 and the proper way would be to move all code into a gateway package. To reduce the refactorings I kept the root src files with "openmotics" as the logger name.

2021-05-28 06:32 UTC, svanscho commented on src/gateway/initialize.py
> +                    logging.getLogger(logger_namespace).setLevel(logging.DEBUG)
good idea

2021-05-28 07:36 UTC, LnL7 commented on src/logs.py
> +            _logger.propagate = True
Is this needed every time the level is changed?

2021-05-28 07:36 UTC, LnL7 commented on src/vpn_service.py
> +                logger.debug('Uploading {} bytes of extra data from {}'.format(len(json.dumps(data).encode('utf-8')), collector_key))
It would be good to use a the lazy formatting from logging instead of str.format a bit more in general to avoid unnecessary work when debugging is not enabled.

2021-05-28 11:56 UTC, svanscho commented on src/cloud/events.py
> +            logger.exception('Error sending events to the cloud')
resolved

2021-05-31 07:13 UTC, LnL7 approved these changes
Can you also update the example config with the new options

2021-05-31 07:45 UTC, LnL7 approved these changes

2021-05-31 07:51 UTC, merged