Feature/impersonate login
openmotics/gateway pull request #751
Opened 2021-07-28 16:39 UTC by ptuytsch

2021-07-29 15:55 UTC, yclybouw requested changes

2021-07-29 15:55 UTC, yclybouw commented on src/gateway/authentication_controller.py
> +            token = self.token_store.create_token(user_to_login, timeout=timeout, login_method=login_method)
Shouldn't the `impersonator` be added to? Because the `user_to_login` might be impersonated.

2021-07-29 15:55 UTC, yclybouw commented on src/gateway/authentication_controller.py
> +    def login_with_user_code(self, pin_code, accept_terms=False, timeout=None, impersonate=None):
I would not allow this with pin_code.

2021-07-29 15:55 UTC, yclybouw commented on src/gateway/authentication_controller.py
> +    def login_with_rfid_tag(self, rfid_tag_string, accept_terms=False, timeout=None, impersonate=None):
I would not allow this wit RFID (only trough the web, thus through username/password).

2021-07-29 15:55 UTC, yclybouw commented on src/gateway/authentication_controller.py
>          if user_id in self.tokens:
This cannot work any more. E.g. a user could be logged in on the display through PIN code, and in the meantime a superuser impersonates for that user. The tokens should be different (e.g. for logging, or for access rights).

2021-07-29 15:55 UTC, yclybouw commented on src/gateway/authentication_controller.py
> +        logger.info(' -*****- New token created: {}'.format(self.tokens[user_id].to_dict()))
Please remove before merging :-)

2021-07-29 15:55 UTC, yclybouw commented on src/gateway/webservice_v1.py
> +        if 'impersonate' in request_body:
I would not allow impersonation for PIN-login.

2021-07-29 15:55 UTC, yclybouw commented on src/gateway/webservice_v1.py
> +        if 'impersonate' in request_body:
I would not allow impersonation for RFID-login.

2021-07-29 15:55 UTC, yclybouw commented on testing/unittests/api_tests/V1/rfid_test.py
> +            auth_token = AuthenticationToken(self.test_admin_1, token='test-token', expire_timestamp=int(time.time() + 3600), login_method=LoginMethod.PASSWORD)
Shouldn't the login method be RFID in this file?

2021-07-30 14:52 UTC, ptuytsch commented on src/gateway/authentication_controller.py
>          if user_id in self.tokens:
Good catch, I changed the key of the dict to an custom object that keeps track of the logged in user and the impersonator to overcome this problem

2021-08-02 07:28 UTC, yclybouw approved these changes

2021-08-02 09:49 UTC, merged