Feature/detailed deliveries api
openmotics/gateway pull request #764
Opened 2021-08-04 16:17 UTC by ptuytsch

2021-08-13 07:57 UTC, yclybouw requested changes

2021-08-13 07:57 UTC, yclybouw commented on src/gateway/delivery_controller.py
> +        query = query.where(Delivery.id > from_id)
As the history is shown in descending order (which makes sense), the "after" or "from_id" should be the upper limit, so: `query.where(Delivery.id < from_id)`

2021-08-13 08:22 UTC, yclybouw commented on src/gateway/delivery_controller.py
> +        query = query.where(Delivery.id > from_id)
This reminds me: from_id should not default to `0` but to "infinity". E.g. set to `None` and do the where conditionally.

2021-08-13 08:42 UTC, ptuytsch commented on src/gateway/delivery_controller.py
> +        query = query.where(Delivery.id > from_id)
indeed good catch! The fix has been pushed

2021-08-13 12:37 UTC, yclybouw approved these changes

2021-08-16 12:40 UTC, yclybouw approved these changes

2021-08-16 12:58 UTC, LnL7 submitted a review, later dismissed

2021-08-16 12:58 UTC, LnL7 commented on src/gateway/api/V1/parcelbox.py
> +    def get_parcelboxes(self, size=None, available=None, show_deliveries=None):
Any user can list pending delivery information?

2021-08-16 13:04 UTC, ptuytsch commented on src/gateway/api/V1/parcelbox.py
> +    def get_parcelboxes(self, size=None, available=None, show_deliveries=None):
Good point, will fix this.

2021-08-16 13:26 UTC, LnL7 approved these changes

2021-08-16 16:01 UTC, merged