thermostats eeprom migration
openmotics/gateway pull request #801
Opened 2021-09-10 13:06 UTC by LnL7

2021-09-20 04:30 UTC, khenderick requested changes

2021-09-20 04:30 UTC, khenderick commented on src/gateway/thermostat/master/thermostat_controller_master.py
> +                                            interval=30, delay=10)
This will add a significant delay to thermostats events, what's the usecase of increasing this? I would expect that if master thermostats are disabled, this controller wouldn't be loaded/started altogether.

Since the migration of thermostats takes place at startup, I would expect that the `start` method would just check the eeprom and refuse to start if it was disabled.

2021-09-20 04:30 UTC, khenderick commented on src/openmotics_service.py
> +        thermostats_gateway_enabled = Feature.select(Feature.enabled) \
Maybe add a comment indicating why the filter is here and not (like for example the platform) inside the migrate method. To make sure that nobody moves it inside and then mark the migration as completed on all gateways when the feature isn't enabled yet.

2021-09-28 07:10 UTC, LnL7 commented on src/gateway/thermostat/master/thermostat_controller_master.py
> +                                            interval=30, delay=10)
The actual master thermostat logic only runs every 1 or 2 minutes so polling every second seems very overkill to me.

2021-09-28 07:21 UTC, khenderick commented on src/gateway/thermostat/master/thermostat_controller_master.py
> +                                            interval=30, delay=10)
Unless you make an actual change (e.g. change mode), then it updates everything (e.g. new setpoints according to this mode) immediately as far as I known. This will now take up to 30 seconds.

2021-09-28 07:55 UTC, khenderick approved these changes

2021-09-28 08:02 UTC, merged