thermostat schedules
openmotics/gateway pull request #968
Opened 2022-01-26 14:23 UTC by LnL7

2022-01-31 13:00 UTC, svanscho requested changes

2022-01-31 13:00 UTC, svanscho commented on src/gateway/pubsub.py
> +    GATEWAY_TOPIC = Literal['config', 'scheduler', 'state']
would change this to INTENT or ACTION

2022-02-02 10:05 UTC, LnL7 commented on src/gateway/scheduling_controller.py
> +            job_id = 'schedule.{0}'.format(schedule_dto.id)
just dto job_id

2022-02-02 10:09 UTC, LnL7 commented on src/gateway/scheduling_controller.py
>      def load_schedules(self, source=Schedule.Sources.GATEWAY):
cleanup

2022-02-02 10:20 UTC, LnL7 commented on src/gateway/scheduling_controller.py
> +            job_id = 'schedule.{0}'.format(schedule_dto.id)
use dto job_id

2022-02-02 12:39 UTC, svanscho approved these changes

2022-02-02 12:41 UTC, merged